Repository OmniSharp/csharp-language-server-protocol, pull requests merged in 2020-09, with the labels that each got.

#344 Fixed DocumentTextSync converter / Added semantic token refresh notification
  src/Client/LanguageClientRegistrationManager.cs
  src/JsonRpc.Generators/GenerateHandlerMethodsGenerator.cs
  src/JsonRpc.Generators/Helpers.cs
  src/Protocol/AbstractHandlers.cs
  src/Protocol/Document/Proposals/ISemanticTokensDeltaHandler.cs
  src/Protocol/LanguageProtocolDelegatingHandlers.cs
  src/Protocol/Models/Proposals/ISemanticTokenResult.cs
  src/Protocol/Models/Proposals/SemanticTokens.cs
  src/Protocol/Models/Proposals/SemanticTokensDelta.cs
  src/Protocol/Models/Proposals/SemanticTokensFullOrDelta.cs
  src/Protocol/Models/Proposals/SemanticTokensFullOrDeltaPartialResult.cs
  src/Protocol/Models/Proposals/SemanticTokensRefreshParams.cs
  src/Protocol/Serialization/Converters/ProgressTokenConverter.cs
  src/Protocol/Serialization/Converters/TextDocumentSyncConverter.cs
  src/Protocol/Workspace/Proposals/ISemanticTokensRefreshHandler.cs
  src/Protocol/WorkspaceNames.cs
  src/Server/LanguageServerServiceCollectionExtensions.cs
  src/Server/Pipelines/SemanticTokensDeltaPipeline.cs
  test/Lsp.Tests/Capabilities/Server/ServerCapabilitiesTests.cs
  test/Lsp.Tests/Capabilities/Server/ServerCapabilitiesTests_$Null_Text_Document_Sync.json
  test/Lsp.Tests/Integration/PartialItemTests.cs
  test/Lsp.Tests/Integration/PartialItemsTests.cs
Labels: chore

#346 fixed an issue where workspace folders could be null, and this would cause issues
  src/Server/LanguageServerWorkspaceFolderManager.cs
  test/Lsp.Tests/Integration/WorkspaceFolderTests.cs
Labels: bug, merge

#348 Fixed case where dynamic registration would fail if Register is called before Initialize
  src/Server/DefaultLanguageServerFacade.cs
  src/Server/LanguageServer.cs
  src/Server/LanguageServerHelpers.cs
  test/Lsp.Tests/Integration/InitializationTests.cs
  test/Lsp.Tests/Integration/WorkspaceFolderTests.cs
Labels: bug

#356 fix ci issue
  Directory.Build.targets
  azure-pipelines.nuke.yml
Labels: chore, merge

#354 Use ConfigureAwait when booting up input stream.
  src/Client/LanguageClient.cs
  src/Dap.Client/DebugAdapterClient.cs
  src/Dap.Server/DebugAdapterServer.cs
  src/Dap.Shared/DapResponseRouter.cs
  src/Dap.Testing/DebugAdapterProtocolTestBase.cs
  src/Dap.Testing/DebugAdapterServerTestBase.cs
  src/JsonRpc.Testing/JsonRpcServerTestBase.cs
  src/JsonRpc.Testing/SettlePipeline.cs
  src/JsonRpc/DelegatingHandlers.cs
  src/JsonRpc/DelegatingJsonNotificationHandler.cs
  src/JsonRpc/DelegatingJsonRequestHandler.cs
  src/JsonRpc/DelegatingNotificationHandler.cs
  src/JsonRpc/DelegatingRequestHandler.cs
  src/JsonRpc/InputHandler.cs
  src/JsonRpc/JsonRpcServer.cs
  src/JsonRpc/OutputHandler.cs
  src/JsonRpc/RequestRouterBase.cs
  src/JsonRpc/ResponseRouter.cs
  src/Protocol/AbstractHandlers.cs
  src/Protocol/Document/ICodeLensHandler.cs
  src/Protocol/Document/ICompletionHandler.cs
  src/Protocol/Document/IDocumentLinkHandler.cs
  src/Protocol/Document/ITextDocumentSyncHandler.cs
  src/Protocol/Document/Proposals/ISemanticTokensDeltaHandler.cs
  src/Protocol/General/IExitHandler.cs
  src/Protocol/General/IShutdownHandler.cs
  src/Protocol/LanguageProtocolDelegatingHandlers.cs
  src/Protocol/Progress/ProgressManager.cs
  src/Protocol/Server/WorkDone/LanguageServerWorkDoneManager.cs
  src/Protocol/Workspace/IExecuteCommandHandler.cs
  src/Server/Configuration/DidChangeConfigurationProvider.cs
  src/Server/LanguageServer.Shutdown.cs
  src/Server/LanguageServer.cs
  src/Server/Pipelines/ResolveCommandPipeline.cs
  src/Server/Pipelines/SemanticTokensDeltaPipeline.cs
  src/Testing/LanguageProtocolTestBase.cs
  src/Testing/LanguageServerTestBase.cs
  test/Lsp.Tests/Integration/LanguageServerConfigurationTests.cs
Labels: bug, merge

#358 Updated subject in fallback handler
  src/Protocol/LanguageProtocolDelegatingHandlers.cs
  test/Dap.Tests/Integration/ProgressTests.cs
  test/Lsp.Tests/Integration/DynamicRegistrationTests.cs
  test/Lsp.Tests/Integration/LanguageServerConfigurationTests.cs
  test/Lsp.Tests/Integration/LanguageServerLoggingTests.cs
  test/Lsp.Tests/Integration/LogMessageTests.cs
  test/Lsp.Tests/Integration/PartialItemsTests.cs
  test/Lsp.Tests/Integration/ProgressTests.cs
  test/Lsp.Tests/Integration/RequestCancellationTests.cs
  test/Lsp.Tests/Integration/ShowMessageTests.cs
  test/TestingUtils/FactWithSkipOnAttribute.cs
  test/TestingUtils/SkipOnPlatform.cs
  test/TestingUtils/TheoryWithSkipOnAttribute.cs
  test/TestingUtils/UnitTestDetector.cs
Labels: bug, merge

#365 disabled failing test
  .build/Build.cs
  README.md
  test/Lsp.Tests/Integration/DynamicRegistrationTests.cs
  test/Lsp.Tests/Integration/PartialItemTests.cs
  test/Lsp.Tests/Integration/PartialItemsTests.cs
  test/TestingUtils/SkipOnPlatform.cs
  test/TestingUtils/TheoryWithSkipOnAttribute.cs
  test/TestingUtils/UnitTestDetector.cs
Labels: bug
